kind: pipeline
name: publish

steps:
- name: publish
  image: plugins/docker
  settings:
    tags: latest
    username: 
      from_secret: harbor_user
    password:
      from_secret: harbor_password
    repo: hub.azoyagroup.com/drone-plugins/drone-dingtalk-message
    registry: hub.azoyagroup.com
  
trigger: 
  branch:
    - master
  event:
    - push